name: Release Helm Charts

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          # The charts directory
          charts_dir: helm
          # The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-helm-{{ .Version }}"
          CR_PAGES_BRANCH: "helm-chart-release"
